name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linter:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: make install
      - name: Run linter
        run: make lint

  tests:
    needs: linter
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pip (Windows only)
        if: runner.os == 'Windows'
        run: pip install --user --upgrade pip
      - name: Install project
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            pip install -e .[test]
          else
            make install
      - name: Run tests
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            pytest -s -vvvv -l --tb=long tests
          else
            make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3